server:
  port: 8181
spring:
  application:
    name: product-service
  datasource:
    url: ${MYSQL_URL}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: 
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"